match = 'vue, jsx'

plugins = [
  '@dvan/plugin-ssg'
]

jsx = true

[html]
title = 'dvan - example'

  [[html.meta]]
  tiangou = 'dao zui hou yi wu suo you.'
  nmsl = 'Your ğŸ is dead!'

  [[html.meta]]
  ningmeng = 'suan le'
  nmsl = 'Your ğŸ is dead!'
